// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
	class LandVehicle;	// External class reference

	class Tank : LandVehicle {
		class NewTurret;	// External class reference
		class Sounds;	// External class reference
		class HitPoints;	// External class reference
	};

	class Tank_F : Tank {

		class HitPoints : HitPoints {
			class HitHull;	// External class reference
			class HitEngine;	// External class reference
			class HitLTrack;	// External class reference
			class HitRTrack;	// External class reference
		};

		class NewTurret;	// External class reference

		class Turrets {
			class MainTurret : NewTurret {
				class ViewOptics;	// External class reference
			};
		};
		class AnimationSources;	// External class reference
        class ViewPilot;	// External class reference
		class ViewOptics;	// External class reference
		class ViewCargo;	// External class reference
		class HeadLimits;	// External class reference
	};

	class UGV_talon_base_F : Tank_F {
		mapSize = 5.33;

		class SpeechVariants {
			class Default {
				speechSingular[] = {"veh_vehicle_UGV_s"};
				speechPlural[] = {"veh_vehicle_UGV_p"};
			};
		};
		textSingular = "$STR_A3_nameSound_veh_vehicle_UGV_s";
		textPlural = "$STR_A3_nameSound_veh_vehicle_UGV_p";
		nameSound = "veh_vehicle_UGV_s";
		author = "$STR_A3_Bohemia_Interactive";
		_generalMacro = "UGV_talon_base_F";
		attenuationEffectType = "CarAttenuation";
		soundGetIn[] = {"", 0.562341, 1};
		soundGetOut[] = {"", 0.562341, 1, 20};
		soundDammage[] = {"", 0.562341, 1};
		soundEngineOnInt[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_int_start", 0.707946, 0.8};
		soundEngineOnExt[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_ext_start", 0.707946, 0.8, 200};
		soundEngineOffInt[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_int_stop", 0.707946, 0.8};
		soundEngineOffExt[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_ext_stop", 0.707946, 0.8, 200};
		buildCrash0[] = {"A3\sounds_f\Vehicles\soft\noises\crash_building_01", 1.77828, 1, 200};
		buildCrash1[] = {"A3\sounds_f\Vehicles\soft\noises\crash_building_02", 1.77828, 1, 200};
		buildCrash2[] = {"A3\sounds_f\Vehicles\soft\noises\crash_building_03", 1.77828, 1, 200};
		buildCrash3[] = {"A3\sounds_f\Vehicles\soft\noises\crash_building_04", 1.77828, 1, 200};
		soundBuildingCrash[] = {"buildCrash0", 0.25, "buildCrash1", 0.25, "buildCrash2", 0.25, "buildCrash3", 0.25};
		WoodCrash0[] = {"A3\sounds_f\Vehicles\soft\noises\crash_mix_wood_01", 1.77828, 1, 200};
		WoodCrash1[] = {"A3\sounds_f\Vehicles\soft\noises\crash_mix_wood_02", 1.77828, 1, 200};
		WoodCrash2[] = {"A3\sounds_f\Vehicles\soft\noises\crash_mix_wood_03", 1.77828, 1, 200};
		WoodCrash3[] = {"A3\sounds_f\Vehicles\soft\noises\crash_mix_wood_04", 1.77828, 1, 200};
		WoodCrash4[] = {"A3\sounds_f\Vehicles\soft\noises\crash_mix_wood_05", 1.77828, 1, 200};
		WoodCrash5[] = {"A3\sounds_f\Vehicles\soft\noises\crash_mix_wood_06", 1.77828, 1, 200};
		soundWoodCrash[] = {"woodCrash0", 0.166, "woodCrash1", 0.166, "woodCrash2", 0.166, "woodCrash3", 0.166, "woodCrash4", 0.166, "woodCrash5", 0.166};
		ArmorCrash0[] = {"A3\sounds_f\Vehicles\soft\noises\crash_vehicle_01", 1.77828, 1, 200};
		ArmorCrash1[] = {"A3\sounds_f\Vehicles\soft\noises\crash_vehicle_02", 1.77828, 1, 200};
		ArmorCrash2[] = {"A3\sounds_f\Vehicles\soft\noises\crash_vehicle_03", 1.77828, 1, 200};
		ArmorCrash3[] = {"A3\sounds_f\Vehicles\soft\noises\crash_vehicle_04", 1.77828, 1, 200};
		soundArmorCrash[] = {"ArmorCrash0", 0.25, "ArmorCrash1", 0.25, "ArmorCrash2", 0.25, "ArmorCrash3", 0.25};

		class Sounds {
			class Idle_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_ext_0800", 0.562341, 0.8, 200};
				frequency = "0.95	+	((rpm/	3200) factor[(300/	3200),(950/	3200)])*0.15";
				volume = "engineOn*camPos*(((rpm/	3200) factor[(300/	3200),(600/	3200)])	*	((rpm/	3200) factor[(960/	3200),(800/	3200)]))";
			};

			class Engine {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_ext_1000rpm", 0.630957, 0.8, 200};
				frequency = "0.8	+	((rpm/	3200) factor[(800/	3200),(1500/	3200)])*0.2";
				volume = "engineOn*camPos*(((rpm/	3200) factor[(800/	3200),(900/	3200)])	*	((rpm/	3200) factor[(1500/	3200),(1100/	3200)]))";
			};

			class Engine1_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_ext_1400rpm", db-3, 0.8, 200};
				frequency = "0.8	+	((rpm/	3200) factor[(1100/	3200),(1950/	3200)])*0.2";
				volume = "engineOn*camPos*(((rpm/	3200) factor[(1050/	3200),(1450/	3200)])	*	((rpm/	3200) factor[(1900/	3200),(1600/	3200)]))";
			};

			class Engine2_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_ext_2000rpm", db-2, 0.8, 250};
				frequency = "0.8	+	((rpm/	3200) factor[(1600/	3200),(2300/	3200)])*0.2";
				volume = "engineOn*camPos*(((rpm/	3200) factor[(1560/	3200),(1880/	3200)])	*	((rpm/	3200) factor[(2350/	3200),(2000/	3200)]))";
			};

			class Engine3_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_ext_2400rpm", db1, 0.8, 300};
				frequency = "0.8	+	((rpm/	3200) factor[(2000/	3200),(2650/	3200)])*0.1";
				volume = "engineOn*camPos*(((rpm/	3200) factor[(1980/	3200),(2300/	3200)])	*	((rpm/	3200) factor[(2660/	3200),(2400/	3200)]))";
			};

			class Engine4_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_ext_2600rpm", db3, 0.8, 350};
				frequency = "0.8	+	((rpm/	3200) factor[(2400/	3200),(3000/	3200)])*0.1";
				volume = "engineOn*camPos*(((rpm/	3200) factor[(2380/	3200),(2640/	3200)])	*	((rpm/	3200) factor[(2990/	3200),(2770/	3200)]))";
			};

			class Engine5_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_ext_3200rpm", db5, 0.8, 400};
				frequency = "0.8	+	((rpm/	3200) factor[(2700/	3200),(3200/	3200)])*0.1";
				volume = "engineOn*camPos*((rpm/	3200) factor[(2700/	3200),(2900/	3200)])";
			};

			class IdleThrust {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_ext_0800_exhaust", db0, 0.8, 250};
				frequency = "0.8	+	((rpm/	3200) factor[(300/	3200),(950/	3200)])*0.15";
				volume = "engineOn*camPos*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/	3200) factor[(300/	3200),(600/	3200)])	*	((rpm/	3200) factor[(960/	3200),(800/	3200)]))";
			};

			class EngineThrust {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_ext_1000rpm_exhaust", db2, 0.8, 300};
				frequency = "0.8	+	((rpm/	3200) factor[(800/	3200),(1500/	3200)])*0.2";
				volume = "engineOn*camPos*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/	3200) factor[(800/	3200),(900/	3200)])	*	((rpm/	3200) factor[(1500/	3200),(1100/	3200)]))";
			};

			class Engine1_Thrust_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_ext_1400rpm_exhaust", db3, 0.8, 350};
				frequency = "0.8	+	((rpm/	3200) factor[(1100/	3200),(1950/	3200)])*0.2";
				volume = "engineOn*camPos*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/	3200) factor[(1050/	3200),(1450/	3200)])	*	((rpm/	3200) factor[(1900/	3200),(1600/	3200)]))";
			};

			class Engine2_Thrust_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_ext_2000rpm_exhaust", db4, 0.8, 400};
				frequency = "0.8	+	((rpm/	3200) factor[(1600/	3200),(2300/	3200)])*0.2";
				volume = "engineOn*camPos*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/	3200) factor[(1560/	3200),(1880/	3200)])	*	((rpm/	3200) factor[(2350/	3200),(2000/	3200)]))";
			};

			class Engine3_Thrust_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_ext_2400rpm_exhaust", db6, 0.8, 450};
				frequency = "0.8	+	((rpm/	3200) factor[(2000/	3200),(2650/	3200)])*0.1";
				volume = "engineOn*camPos*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/	3200) factor[(1980/	3200),(2300/	3200)])	*	((rpm/	3200) factor[(2660/	3200),(2400/	3200)]))";
			};

			class Engine4_Thrust_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_ext_2600rpm_exhaust", db6, 0.8, 450};
				frequency = "0.8	+	((rpm/	3200) factor[(2400/	3200),(3000/	3200)])*0.1";
				volume = "engineOn*camPos*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/	3200) factor[(2380/	3200),(2640/	3200)])	*	((rpm/	3200) factor[(2990/	3200),(2770/	3200)]))";
			};

			class Engine5_Thrust_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_ext_3200rpm_exhaust", 2.23872, 0.8, 500};
				frequency = "0.8	+	((rpm/	3200) factor[(2700/	3200),(3200/	3200)])*0.1";
				volume = "engineOn*camPos*(0.4+(0.6*(thrust factor[0.1,1])))*((rpm/	3200) factor[(2700/	3200),(2900/	3200)])";
			};

			class Idle_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_int_0800", 0.398107, 0.8};
				frequency = "0.8	+	((rpm/	3200) factor[(300/	3200),(950/	3200)])*0.15";
				volume = "engineOn*(1-camPos)*(((rpm/	3200) factor[(300/	3200),(600/	3200)])	*	((rpm/	3200) factor[(960/	3200),(800/	3200)]))";
			};

			class Engine_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_int_1000rpm", db-7, 0.8};
				frequency = "0.8	+	((rpm/	3200) factor[(800/	3200),(1500/	3200)])*0.2";
				volume = "engineOn*(1-camPos)*(((rpm/	3200) factor[(800/	3200),(900/	3200)])	*	((rpm/	3200) factor[(1500/	3200),(1100/	3200)]))";
			};

			class Engine1_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_int_1400rpm", db-6, 0.8};
				frequency = "0.8	+	((rpm/	3200) factor[(1100/	3200),(1950/	3200)])*0.2";
				volume = "engineOn*(1-camPos)*(((rpm/	3200) factor[(1050/	3200),(1450/	3200)])	*	((rpm/	3200) factor[(1900/	3200),(1600/	3200)]))";
			};

			class Engine2_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_int_2000rpm", db-6, 0.8};
				frequency = "0.8	+	((rpm/	3200) factor[(1600/	3200),(2300/	3200)])*0.2";
				volume = "engineOn*(1-camPos)*(((rpm/	3200) factor[(1560/	3200),(1880/	3200)])	*	((rpm/	3200) factor[(2350/	3200),(2000/	3200)]))";
			};

			class Engine3_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_int_2400rpm", 0.562341, 0.8};
				frequency = "0.8	+	((rpm/	3200) factor[(2000/	3200),(2650/	3200)])*0.1";
				volume = "engineOn*(1-camPos)*(((rpm/	3200) factor[(1980/	3200),(2300/	3200)])	*	((rpm/	3200) factor[(2660/	3200),(2400/	3200)]))";
			};

			class Engine4_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_int_2600rpm", 0.562341, 0.8};
				frequency = "0.8	+	((rpm/	3200) factor[(2400/	3200),(3000/	3200)])*0.1";
				volume = "engineOn*(1-camPos)*(((rpm/	3200) factor[(2380/	3200),(2640/	3200)])	*	((rpm/	3200) factor[(2990/	3200),(2770/	3200)]))";
			};

			class Engine5_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_int_3200rpm", 0.630957, 0.8};
				frequency = "0.8	+	((rpm/	3200) factor[(2700/	3200),(3200/	3200)])*0.1";
				volume = "engineOn*(1-camPos)*((rpm/	3200) factor[(2700/	3200),(2900/	3200)])";
			};

			class IdleThrust_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_int_0800_exhaust", db-6, 0.8};
				frequency = "0.8	+	((rpm/	3200) factor[(300/	3200),(950/	3200)])*0.15";
				volume = "engineOn*(1-camPos)*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/	3200) factor[(300/	3200),(600/	3200)])	*	((rpm/	3200) factor[(960/	3200),(800/	3200)]))";
			};

			class EngineThrust_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_int_1000rpm_exhaust", 0.562341, 0.8};
				frequency = "0.8	+	((rpm/	3200) factor[(800/	3200),(1500/	3200)])*0.2";
				volume = "engineOn*(1-camPos)*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/	3200) factor[(800/	3200),(900/	3200)])	*	((rpm/	3200) factor[(1500/	3200),(1100/	3200)]))";
			};

			class Engine1_Thrust_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_int_1400rpm_exhaust", 0.630957, 0.8};
				frequency = "0.8	+	((rpm/	3200) factor[(1100/	3200),(1950/	3200)])*0.2";
				volume = "engineOn*(1-camPos)*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/	3200) factor[(1050/	3200),(1450/	3200)])	*	((rpm/	3200) factor[(1900/	3200),(1600/	3200)]))";
			};

			class Engine2_Thrust_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_int_2000rpm_exhaust", 0.630957, 0.8};
				frequency = "0.8	+	((rpm/	3200) factor[(1600/	3200),(2300/	3200)])*0.2";
				volume = "engineOn*(1-camPos)*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/	3200) factor[(1560/	3200),(1880/	3200)])	*	((rpm/	3200) factor[(2350/	3200),(2000/	3200)]))";
			};

			class Engine3_Thrust_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_int_2400rpm_exhaust", db-3, 0.8};
				frequency = "0.8	+	((rpm/	3200) factor[(2000/	3200),(2650/	3200)])*0.1";
				volume = "engineOn*(1-camPos)*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/	3200) factor[(1980/	3200),(2300/	3200)])	*	((rpm/	3200) factor[(2660/	3200),(2400/	3200)]))";
			};

			class Engine4_Thrust_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_int_2600rpm_exhaust", db-2, 0.8};
				frequency = "0.8	+	((rpm/	3200) factor[(2400/	3200),(3000/	3200)])*0.1";
				volume = "engineOn*(1-camPos)*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/	3200) factor[(2380/	3200),(2640/	3200)])	*	((rpm/	3200) factor[(2990/	3200),(2770/	3200)]))";
			};

			class Engine5_Thrust_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\UGV_01\UGV_01_int_3200rpm_exhaust", db0, 0.8};
				frequency = "0.8	+	((rpm/	3200) factor[(2700/	3200),(3200/	3200)])*0.1";
				volume = "engineOn*(1-camPos)*(0.4+(0.6*(thrust factor[0.1,1])))*((rpm/	3200) factor[(2700/	3200),(2900/	3200)])";
			};

			class Movement {
				sound = "soundEnviron";
				frequency = "1";
				volume = "0";
			};

			class TiresRockOut {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\ext_tires_dirt_soft_1", db0, 1.0, 60};
				frequency = "1";
				volume = "camPos*rock*(speed factor[2, 20])";
			};

			class TiresSandOut {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\ext-tires-sand1", db0, 1.0, 60};
				frequency = "1";
				volume = "camPos*sand*(speed factor[2, 20])";
			};

			class TiresGrassOut {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\ext_tires_dirt_soft_2", db0, 1.0, 60};
				frequency = "1";
				volume = "camPos*grass*(speed factor[2, 20])";
			};

			class TiresMudOut {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\ext-tires-mud2", db0, 1.0, 60};
				frequency = "1";
				volume = "camPos*mud*(speed factor[2, 20])";
			};

			class TiresGravelOut {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\ext_tires_gravel_1", db0, 1.0, 60};
				frequency = "1";
				volume = "camPos*gravel*(speed factor[2, 20])";
			};

			class TiresAsphaltOut {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\ext_tires_asfalt_2", db0, 1.0, 60};
				frequency = "1";
				volume = "camPos*asphalt*(speed factor[2, 20])";
			};

			class NoiseOut {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\noise_int_car_3", db0, 1.0, 90};
				frequency = "1";
				volume = "camPos*(damper0 max 0.02)*(speed factor[0, 8])";
			};

			class TiresRockIn {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\int_tires_dirt_soft_1", db-3, 1.0};
				frequency = "1";
				volume = "(1-camPos)*rock*(speed factor[2, 20])";
			};

			class TiresSandIn {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\int-tires-sand2", db-3, 1.0};
				frequency = "1";
				volume = "(1-camPos)*sand*(speed factor[2, 20])";
			};

			class TiresGrassIn {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\int_tires_dirt_soft_2", db-3, 1.0};
				frequency = "1";
				volume = "(1-camPos)*grass*(speed factor[2, 20])";
			};

			class TiresMudIn {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\int-tires-mud2", db-3, 1.0};
				frequency = "1";
				volume = "(1-camPos)*mud*(speed factor[2, 20])";
			};

			class TiresGravelIn {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\int_tires_gravel_1", db-3, 1.0};
				frequency = "1";
				volume = "(1-camPos)*gravel*(speed factor[2, 20])";
			};

			class TiresAsphaltIn {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\int_tires_asfalt_2", db-3, 1.0};
				frequency = "1";
				volume = "(1-camPos)*asphalt*(speed factor[2, 20])";
			};

			class NoiseIn {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\noise_int_car_3", db-3, 1.0};
				frequency = "1";
				volume = "(damper0 max 0.1)*(speed factor[0, 8])*(1-camPos)";
			};

			class breaking_ext_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_04", 0.562341, 1, 100};
				frequency = 1;
				volume = "engineOn*camPos*(LongSlipDrive Factor[-0.2, -0.4])*(Speed Factor[2, 10])";
			};

			class acceleration_ext_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02", 0.562341, 1, 100};
				frequency = 1;
				volume = "engineOn*camPos*(LongSlipDrive Factor[0.2, 0.4])*(Speed Factor[10, 1])";
			};

			class turn_left_ext_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02", 0.562341, 1, 100};
				frequency = 1;
				volume = "engineOn*camPos*(latSlipDrive Factor[0.15, 0.4])*(Speed Factor[0, 10])";
			};

			class turn_right_ext_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02", 0.562341, 1, 100};
				frequency = 1;
				volume = "engineOn*camPos*(latSlipDrive Factor[-0.15, -0.4])*(Speed Factor[0, 10])";
			};

			class breaking_ext_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_04", 0.562341, 1, 100};
				frequency = 1;
				volume = "engineOn*camPos*(LongSlipDrive Factor[-0.2, -0.4])*(Speed Factor[2, 10])";
			};

			class acceleration_ext_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02", 0.562341, 1, 100};
				frequency = 1;
				volume = "engineOn*camPos*(LongSlipDrive Factor[0.2, 0.4])*(Speed Factor[10, 1])";
			};

			class turn_left_ext_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02", 0.562341, 1, 100};
				frequency = 1;
				volume = "engineOn*camPos*(latSlipDrive Factor[0.15, 0.4])*(Speed Factor[0, 10])";
			};

			class turn_right_ext_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02", 0.562341, 1, 100};
				frequency = 1;
				volume = "engineOn*camPos*(latSlipDrive Factor[-0.15, -0.4])*(Speed Factor[0, 10])";
			};

			class breaking_int_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_04_int", db-7, 1};
				frequency = 1;
				volume = "engineOn*(1-camPos)*(LongSlipDrive Factor[-0.4, -0.8])*(Speed Factor[2, 6])";
			};

			class acceleration_int_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02_int", db-7, 1};
				frequency = 1;
				volume = "engineOn*(1-camPos)*(LongSlipDrive Factor[0.4, 0.8])*(Speed Factor[10, 1])";
			};

			class turn_left_int_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02_int", 0.562341, 1};
				frequency = 1;
				volume = "engineOn*(1-camPos)*(latSlipDrive Factor[0.15, 0.4])*(Speed Factor[0, 10])";
			};

			class turn_right_int_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02_int", 0.562341, 1};
				frequency = 1;
				volume = "engineOn*(1-camPos)*(latSlipDrive Factor[-0.15, -0.4])*(Speed Factor[0, 10])";
			};

			class breaking_int_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_04_int", db-7, 1};
				frequency = 1;
				volume = "engineOn*(1-camPos)*(LongSlipDrive Factor[-0.4, -0.8])*(Speed Factor[2, 6])";
			};

			class acceleration_int_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02_int", db-7, 1};
				frequency = 1;
				volume = "engineOn*(1-camPos)*(LongSlipDrive Factor[0.4, 0.8])*(Speed Factor[10, 1])";
			};

			class turn_left_int_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02_int", 0.562341, 1};
				frequency = 1;
				volume = "engineOn*(1-camPos)*(latSlipDrive Factor[0.15, 0.4])*(Speed Factor[1, 10])";
			};

			class turn_right_int_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02_int", 0.562341, 1};
				frequency = 1;
				volume = "engineOn*(1-camPos)*(latSlipDrive Factor[-0.15, -0.4])*(Speed Factor[1, 10])";
			};
		};
		simulation = "tankX";
		enginePower = 485;
		maxOmega = 241;
		peakTorque = 2610;
		torqueCurve[] = {{(610/2300), 0}, {(1000/2300), (1600/2610)}, {(1400/2300), (2610/2610)}, {(2300/2300), (1900/2610)}, {(4700/2300), (0/2610)}};
		thrustDelay = 0.3;
		clutchStrength = 60.0;
		fuelCapacity = 770;
		brakeIdleSpeed = 1.78;
		latency = 0.1;
		tankTurnForce = 1300000;
		normalSpeedForwardCoef = 0.5;
		idleRpm = 610;
		redRpm = 2300;
		engineLosses = 25;
		transmissionLosses = 15;

		class complexGearbox {
			GearboxRatios[] = {"R1", -2.235, "N", 0, CD0, 2*(0.75^(-10)), CD1, 2*(0.75^(-9)), CD2, 2*(0.75^(-8)), CD3, 2*(0.75^(-7)), CD4, 2*(0.75^(-6)), CD5, 2*(0.75^(-5)), CD6, 2*(0.75^(-4)), CD7, 2*(0.75^(-3)), CD8, 2*(0.75^(-2)), CD9, 2*(0.75^(-1)), "D1", 2*(0.75^0), "D2", 2*(0.75^1), "D3", 2*(0.75^2), "D4", 2*(0.75^3)};
			TransmissionRatios[] = {"High", 5};
			gearBoxMode = "auto";
			moveOffGear = 1;
			driveString = "D";
			neutralString = "N";
			reverseString = "R";
			transmissionDelay = 0;
		};

		class Wheels {
			class L2 {
				boneName = "wheel_podkoloL2";
				center = "wheel_1_2_axis";
				boundary = "wheel_1_2_bound";
				damping = 75.0;
				steering = 0;
				side = "left";
				weight = 5;
				mass = 5;
				MOI = 250;
				latStiffX = 25;
				latStiffY = 280;
				longitudinalStiffnessPerUnitGravity = 100000;
				maxBrakeTorque = 10000;
				sprungMass = 20.0;
				springStrength = 500;
				springDamperRate = 40;
				dampingRate = 1.0;
				dampingRateInAir = 4864.0;
				dampingRateDamaged = 10.0;
				dampingRateDestroyed = 10000;
				maxDroop = 0.01;
				maxCompression = 0.01;
				frictionVsSlipGraph[] = {{0, 5}, {0.5, 5}, {1, 5}};
			};

			class L3 : L2 {
				boneName = "wheel_podkoloL3";
				center = "wheel_1_3_axis";
				boundary = "wheel_1_3_bound";
				sprungMass = 5.0;
				springStrength = 500;
				springDamperRate = 40;
				maxDroop = 0.01;
				maxCompression = 0.01;
			};

			class L1 : L2 {
				boneName = "wheel_podkoloL1";
				center = "wheel_1_1_axis";
				boundary = "wheel_1_1_bound";
				sprungMass = 5.0;
				springStrength = 500;
				springDamperRate = 40;
				maxDroop = 0.01;
				maxCompression = 0.01;
			};

			class R2 : L2 {
				boneName = "wheel_podkoloP2";
				center = "wheel_2_2_axis";
				boundary = "wheel_2_2_bound";
				side = "right";
			};

			class R3 : R2 {
				boneName = "wheel_podkoloP3";
				center = "wheel_2_3_axis";
				boundary = "wheel_2_3_bound";
				sprungMass = 5.0;
				springStrength = 500;
				springDamperRate = 40;
				maxDroop = 0.01;
				maxCompression = 0.01;
			};

			class R1 : R2 {
				boneName = "wheel_podkoloP1";
				center = "wheel_2_1_axis";
				boundary = "wheel_2_1_bound";
				sprungMass = 5.0;
				springStrength = 500;
				springDamperRate = 40;
				maxDroop = 0.01;
				maxCompression = 0.01;
			};
		};

		displayName = "$STR_A3_CfgVehicles_UGV_01_Base0";

		class Library {
			libTextDesc = "$STR_A3_CfgVehicles_UGV_01_Base_Library0";
		};
		vehicleClass = "Autonomous";
		model = "\talon\talon";
		picture = "\A3\Drones_F\soft_f_gamma\UGV_01\Data\UI\portrait_UGV_01_CA.paa";
		Icon = "\A3\Drones_F\soft_f_gamma\UGV_01\Data\UI\map_UGV_01_CA.paa";
		cost = 200000;
		unitInfoType = "RscOptics_AV_driver";
		radarType = 8;
		driverCanSee = 2+4+8+16+32;
		gunnerCanSee = 2+4+8+16+32;
		isUav = 1;
		uavCameraDriverPos = "PiP0_pos";
		uavCameraDriverDir = "PiP0_dir";
		extCameraPosition[] = {0, 1.5, -5.0};

		class AnimationSources : AnimationSources {
			class Turret {
				source = "user";
				animPeriod = 1;
				initPhase = 1;
			};

			class MainTurret : Turret {};

			class MainGun : Turret {};

		};
		cargoCanControlUAV = 0;
		maxSpeed = 20;	// max speed on level road, km/h
		terrainCoef = 1.2;
		turnCoef = 3;
		steerAheadSimul = 0.5;
		steerAheadPlan = 0.35;
		predictTurnPlan = 0.8;
		predictTurnSimul = 0.6;
		precision = 20;
		brakeDistance = 3.0;	// vehicle movement precision
		acceleration = 15;
		armor = 100;
		armorStructural = 4;
		damageResistance = 0.00719;
		canFloat = false;
		enableGPS = 1;
		killFriendlyExpCoef = 0.1;
		fuelExplosionPower = 2;
		wheelDamageThreshold = 0.7;
		wheelDestroyThreshold = 0.99;
		wheelDamageRadiusCoef = 0.95;
		wheelDestroyRadiusCoef = 0.75;
		transportMaxBackpacks = 6;
		transportSoldier = 0;
		commanderCanSee = 31;
		driverAction = "Disabled";
		cargoAction[] = {"driver_ugv_01"};
		showNVGCargo[] = {1};
		driverForceOptics = true;
		driverOpticsModel = "A3\drones_f\Weapons_F_Gamma\Reticle\UGV_01_Optics_Driver_F.p3d";
		memoryPointDriverOptics = "PiP0_pos";
		driverCompartments = "Compartment3";
		cargoCompartments[] = {"Compartment2"};
		forceHideDriver = true;

		class ViewOptics : ViewOptics {
			visionMode[] = {"Normal", NVG};
			initFov = 0.85;
			minFov = 0.85;
			maxFov = 0.85;
		};
		cargoIsCoDriver[] = {0, 0};
		ejectDeadGunner = false;
		ejectDeadCargo = false;
		ejectDeadDriver = false;
		ejectDeadCommander = 0;

	class HitPoints : HitPoints {
			class HitHull : HitHull {
				armor = 1.0;
				material = -1;
				name = "telo";
				visual = "zbytek";
				passThrough = true;
				minimalHit = 0.2;
				explosionShielding = 0.2;
				radius = 0.025;
			};

			class HitEngine : HitEngine {
				armor = 0.8;
				material = -1;
				name = "motor";
				passThrough = 0.5;
				minimalHit = 0.2;
				explosionShielding = 0.2;
				radius = 0.035;
			};

			class HitLTrack : HitLTrack {
				armor = 0.6;
				material = -1;
				name = "pas_L";
				passThrough = false;
				minimalHit = 0.15;
				explosionShielding = 0.4;
				radius = 0.03;
			};

			class HitRTrack : HitRTrack {
				armor = 0.6;
				material = -1;
				name = "pas_P";
				passThrough = false;
				minimalHit = 0.15;
				explosionShielding = 0.4;
				radius = 0.03;
			};
		};
		weapons[] = {""};
		magazines[] = {""};

		// threat (VSoft, VArmor, VAir), how threatening vehicle is to unit types
		threat[] = {1, 0.8, 0.3};

		hiddenSelections[] = {"camo1", "camo2", "camo3"};
		transportMaxWeapons = 8;
		transportMaxMagazines = 64;
		maximumLoad = 1000;

		class TransportBackpacks {};

		class TransportMagazines {};

		class TransportWeapons {};

		class TransportItems {
			class _xx_FirstAidKit {
				name = "FirstAidKit";
				count = 4;
			};
		};

		class Damage {
			tex[] = {};
			mat[] = {"A3\Drones_F\soft_f_gamma\UGV_01\Data\UGV_01_ext.rvmat", "A3\Drones_F\soft_f_gamma\UGV_01\Data\UGV_01_ext_damage.rvmat", "A3\Drones_F\soft_f_gamma\UGV_01\Data\UGV_01_ext_destruct.rvmat", "A3\Drones_F\soft_f_gamma\UGV_01\Data\UGV_01_int.rvmat", "A3\Drones_F\soft_f_gamma\UGV_01\Data\UGV_01_int_damage.rvmat", "A3\Drones_F\soft_f_gamma\UGV_01\Data\UGV_01_int_destruct.rvmat"};
		};
	};

		class UGV_talon_rcws_base_F : UGV_talon_base_F {
		author = "Specter";
		_generalMacro = "UGV_01_rcws_base_F";
		displayName = "$STR_A3_CfgVehicles_UGV_01_RCWS_Base0";

		class Library {
			libTextDesc = "$str_a3_cfgvehicles_ugv_01_base_library0";
		};
		model = "\talon\talon";
		picture = "\A3\Drones_F\soft_f_gamma\UGV_01\Data\UI\portrait_UGV_01_CA.paa";
		Icon = "\A3\Drones_F\soft_f_gamma\UGV_01\Data\UI\map_UGV_01_RCWS_CA.paa";
		cost = 250000;
		uavCameraGunnerPos = "PiP1_pos";
		uavCameraGunnerDir = "PiP1_dir";

		class AnimationSources : AnimationSources {
			class Turret {
				source = "user";
				animPeriod = 1;
				initPhase = 0;
			};
			class MainGun {};
			class MainTurret {};
		};

		class Turrets : Turrets {
			class MainTurret : NewTurret {
				isCopilot = 0;
				dontCreateAI = 0;
				body = "mainTurret";
				gun = "mainGun";
				memoryPointGunnerOptics = "PiP1_pos";
				gunnerForceOptics = true;
				gunnerOpticsModel = "A3\drones_f\Weapons_F_Gamma\Reticle\UAV_Optics_Gunner_F.p3d";
				turretInfoType = "RscOptics_UGV_gunner";
				weapons[] = {"put"};
				magazines[] = {};
				soundServo[] = {"A3\sounds_f\dummysound", db-40, 1.0, 10};
                maxHorizontalRotSpeed = 1.8;	// 1 = 45°/sec
                maxVerticalRotSpeed = 1.8;		// 1 = 45°/sec
				minElev = -25;
				maxElev = 30;
                initElev=0;
                minTurn=-75;
                maxTurn=+75;
                initTurn=0;
				forceHideGunner = true;
				outGunnerMayFire = true;
				discreteDistance[] = {1, 5, 10};
				discreteDistanceInitIndex = 2;
				stabilizedInAxes = StabilizedInAxesBoth;
				gunnerInAction = "Disabled";
				gunnerAction = "Disabled";

				class ViewOptics : RCWSOptics {
					visionMode[] = {"Normal", "TI"};
					initFov = 0.75;
					maxFov = 0.75;
					minFov = 0.375;
					directionStabilized = 1;
				};
			};
		};
	};

	class B_UGV_talon_rcws_F : UGV_talon_rcws_base_F {
		author = "Specter";
		_generalMacro = "B_UGV_talon_rcws_F";
		scope = public;
		crew = B_UAV_AI;
		typicalCargo[] = {"B_Soldier_F"};
		side = TWest;
		faction = BLU_F;
		hiddenSelectionsTextures[] = {"\A3\Drones_F\soft_f_gamma\UGV_01\data\UGV_01_ext_co.paa", "\A3\Drones_F\soft_f_gamma\UGV_01\data\UGV_01_int_co.paa", "\A3\Data_F\Vehicles\Turret_co.paa"};
	};



};
